### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lukepalmer** [zbigg/bashfoo#1]
This looks really useful- would you mind adding an open source license so that others can include this in projects?

**Comment by zbigg** [comment]
Wow. Never thought that it will be useful to anyone.

I think that MIT is best one. I will push it mabe even today.

**Comment by lukepalmer** [comment]
Yup- I was just about to write memoization and way better if I just use yours. Thank you!

**Comment by zbigg** [comment]
Published under MIT license few minutes ago.

**Comment by zbigg** [comment]
Now waiting for Code of Conduct request ;)
